version: "2"
linters:
  default: none
  enable:
  # Enabled by default -- Few false positives
  - errcheck
  - govet
  - ineffassign
  - staticcheck
  - unused

  # The following are additionally enabled
  - containedctx
  - gocritic
  - godot
  - gosec
  - misspell
  - nakedret
  - nlreturn # new line before return
  - noctx # check requests for context
  - paralleltest
  - revive
  - testifylint # use proper testify methods
  - unconvert # Remove unnecessary type conversions
  - unparam
  - whitespace
  - wsl
  settings:
    nakedret:
      max-func-lines: 5
  exclusions:
    generated: lax
    presets:
    - common-false-positives
    - std-error-handling
    - comments
issues:
  max-issues-per-linter: 50
  max-same-issues: 8
  fix: true
formatters:
  enable:
  - goimports
