# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  name: Vector Sigma
  version: "0.1.0"

tasks:
  default:
    silent: true
    cmds:
    - echo "Welcome to {{.name}}"
    - task -l

  test:
    desc: Run all tests
    silent: true
    cmds:
    - go run github.com/onsi/ginkgo/v2/ginkgo run --covermode set --coverprofile cover.out ./...

  update-golden-files:
    desc: Update golden files
    silent: true
    cmds:
    - go run github.com/onsi/ginkgo/v2/ginkgo run --covermode set --coverprofile cover.out cmd -- -update

  install:
    desc: Install {{ .name }}
    deps:
    - test
    cmds:
    - go install
