// This file is generated by VectorSigma . DO NOT EDIT.
package orderprocessor

import (
	"fmt"
	"log/slog"
	"os"
)

type (
	StateName  string
	ActionName string
	GuardName  string
)

const (
	ChargingPayment     StateName = "ChargingPayment"
	Completed           StateName = "Completed"
	ErrorHandling       StateName = "ErrorHandling"
	FinalState          StateName = "FinalState"
	FulfillingOrder     StateName = "FulfillingOrder"
	InitialState        StateName = "InitialState"
	Initializing        StateName = "Initializing"
	InitializingContext StateName = "InitializingContext"
	LoadingSubject      StateName = "LoadingSubject"
	Processing          StateName = "Processing"
	ValidatingOrder     StateName = "ValidatingOrder"
)

const (
	ChargePayment     ActionName = "ChargePayment"
	FulfillOrder      ActionName = "FulfillOrder"
	HandleError       ActionName = "HandleError"
	InitializeContext ActionName = "InitializeContext"
	LoadSubject       ActionName = "LoadSubject"
	ValidateOrder     ActionName = "ValidateOrder"
)

const ()

const maxStateDepth = 5

// Action represents a function that can be executed in a state and may return an error.
type Action struct {
	Name    ActionName
	Params  []string
	Execute func(...string) error
}

// Guard represents a function that returns a boolean indicating if a transition should occur.
type Guard struct {
	Name   GuardName
	Params []string
	Check  func(...string) bool
	Action *Action
}

// StateConfig holds the actions and guards for a state.
type StateConfig struct {
	Actions         []Action
	Guards          []Guard
	Transitions     map[int]StateName // Maps guard index to the next state
	Composite       CompositeState
	ErrorTransition StateName // Target state for error events (empty if not defined)
}

type CompositeState struct {
	InitialState StateName
	StateConfigs map[StateName]StateConfig
}

// VectorSigma represents the Finite State Machine (fsm) for VectorSigma.
type OrderProcessor struct {
	Context       *Context
	CurrentState  StateName
	ExtendedState *ExtendedState
	StateConfigs  map[StateName]StateConfig
}

// New initializes a new FSM.
func New() *OrderProcessor {
	logLevel := new(slog.LevelVar)
	logLevel.Set(slog.LevelInfo)

	if os.Getenv("ORDERPROCESSOR_DEBUG") != "" {
		logLevel.Set(slog.LevelDebug)
	}

	fsm := &OrderProcessor{
		Context:       &Context{Logger: slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: logLevel}))},
		CurrentState:  InitialState,
		ExtendedState: &ExtendedState{},
		StateConfigs:  make(map[StateName]StateConfig),
	}
	fsm.StateConfigs[Completed] = StateConfig{
		Actions: []Action{},
		Guards:  []Guard{},
		Transitions: map[int]StateName{
			0: FinalState,
		},
	}
	fsm.StateConfigs[ErrorHandling] = StateConfig{
		Actions: []Action{
			{Name: HandleError, Execute: fsm.HandleErrorAction, Params: []string{}},
		},
		Guards: []Guard{},
		Transitions: map[int]StateName{
			0: Completed,
		},
	}

	fsm.StateConfigs[InitialState] = StateConfig{
		Actions: []Action{},
		Guards:  []Guard{},
		Transitions: map[int]StateName{
			0: Initializing,
		},
	}
	fsm.StateConfigs[Initializing] = StateConfig{
		Actions: []Action{},
		Guards:  []Guard{},
		Transitions: map[int]StateName{
			0: Processing,
		},
		Composite: CompositeState{
			InitialState: InitialState,
			StateConfigs: map[StateName]StateConfig{

				InitialState: {
					Actions: []Action{},
					Guards:  []Guard{},
					Transitions: map[int]StateName{
						0: InitializingContext,
					},
				},
				InitializingContext: {
					Actions: []Action{
						{Name: InitializeContext, Execute: fsm.InitializeContextAction, Params: []string{}},
					},
					Guards: []Guard{},
					Transitions: map[int]StateName{
						0: LoadingSubject,
					},
				},
				LoadingSubject: {
					Actions: []Action{
						{Name: LoadSubject, Execute: fsm.LoadSubjectAction, Params: []string{}},
					},
					Guards: []Guard{},
					Transitions: map[int]StateName{
						0: FinalState,
					},
				},
			},
		},
		ErrorTransition: ErrorHandling,
	}
	fsm.StateConfigs[Processing] = StateConfig{
		Actions: []Action{},
		Guards:  []Guard{},
		Transitions: map[int]StateName{
			0: Completed,
		},
		Composite: CompositeState{
			InitialState: InitialState,
			StateConfigs: map[StateName]StateConfig{
				ChargingPayment: {
					Actions: []Action{
						{Name: ChargePayment, Execute: fsm.ChargePaymentAction, Params: []string{}},
					},
					Guards: []Guard{},
					Transitions: map[int]StateName{
						0: FulfillingOrder,
					},
				},

				FulfillingOrder: {
					Actions: []Action{
						{Name: FulfillOrder, Execute: fsm.FulfillOrderAction, Params: []string{}},
					},
					Guards: []Guard{},
					Transitions: map[int]StateName{
						0: FinalState,
					},
				},
				InitialState: {
					Actions: []Action{},
					Guards:  []Guard{},
					Transitions: map[int]StateName{
						0: ValidatingOrder,
					},
				},
				ValidatingOrder: {
					Actions: []Action{
						{Name: ValidateOrder, Execute: fsm.ValidateOrderAction, Params: []string{}},
					},
					Guards: []Guard{},
					Transitions: map[int]StateName{
						0: ChargingPayment,
					},
				},
			},
		},
		ErrorTransition: ErrorHandling,
	}

	return fsm
}

// Run handles the state transitions based on the current state.
func (fsm *OrderProcessor) Run() error {
	return run(fsm, fsm.StateConfigs, 0)
}

func run(fsm *OrderProcessor, stateConfigs map[StateName]StateConfig, depth int) error {
	if depth > maxStateDepth {
		return fmt.Errorf("max state depth exceeded")
	}

	for {
		// If we are in the FinalState, exit the FSM
		if fsm.CurrentState == FinalState {
			// Reset to the Initial State in case the FSM is run in a loop
			fsm.CurrentState = InitialState

			return fsm.ExtendedState.Error
		}

		config, exists := stateConfigs[fsm.CurrentState]

		if !exists {
			fsm.Context.Logger.Error("missing config", "state", fsm.CurrentState)

			return fmt.Errorf("missing config for state: %s", fsm.CurrentState)
		}

		if config.Composite.StateConfigs != nil {
			parentState := fsm.CurrentState
			// Recursively run the composite state machine
			fsm.CurrentState = config.Composite.InitialState
			fsm.Context.Logger.Debug("entering composite state", "state", parentState, "initial", fsm.CurrentState)
			err := run(fsm, config.Composite.StateConfigs, depth+1)
			if err != nil {
				fsm.Context.Logger.Error("composite state machine failed", "state", fsm.CurrentState, "error", err)
				fsm.ExtendedState.Error = err

				// Check if there's an error event transition defined for this composite state
				if config.ErrorTransition != "" {
					fsm.Context.Logger.Debug("error event triggered", "from", parentState, "to", config.ErrorTransition)
					fsm.CurrentState = config.ErrorTransition
					continue
				}
			}

			fsm.Context.Logger.Debug("exiting composite state", "state", parentState)
			fsm.CurrentState = parentState
		} else {
			// Execute all actions for the current state
			err := runAllActions(fsm.Context, fsm.CurrentState, config.Actions)
			if err != nil {
				fsm.Context.Logger.Error("action failed", "state", fsm.CurrentState, "error", err)
				fsm.ExtendedState.Error = err

				// Check if there's an error event transition defined for this state
				if config.ErrorTransition != "" {
					fsm.Context.Logger.Debug("error event triggered", "from", fsm.CurrentState, "to", config.ErrorTransition)
					fsm.CurrentState = config.ErrorTransition
					continue
				}
			}
		}

		// Check guards and determine the next state
		nextState, err := runAllGuards(fsm.Context, fsm.CurrentState, config)
		if err != nil {
			// Guarded actions will always transition to the FinalState
			fsm.ExtendedState.Error = err
			fsm.CurrentState = FinalState
		}
		if nextState != "" {
			fsm.CurrentState = nextState

			continue
		}

		// Check for unguarded transition
		if nextState, exists := config.Transitions[len(config.Guards)]; exists {
			fsm.Context.Logger.Debug("unguarded transition", "current", fsm.CurrentState, "next", nextState)
			fsm.CurrentState = nextState
		}
	}

}

func runAllActions(context *Context, currentState StateName, actions []Action) error {
	for _, action := range actions {
		context.Logger.Debug("executing", "action", action.Name, "state", currentState)

		if err := action.Execute(action.Params...); err != nil {
			return err
		}
	}

	return nil
}

func runAllGuards(context *Context, currentState StateName, config StateConfig) (StateName, error) {
	for guardIndex, guard := range config.Guards {
		if guard.Check(guard.Params...) {
			if guard.Action != nil {
				action := guard.Action
				if err := action.Execute(action.Params...); err != nil {
					context.Logger.Debug("guarded action failed", "state", currentState,
						"guard", guard.Name, "action", action.Name, "error", err)

					return "", err
				}
			}

			// Transition to the state mapped to this guard index
			if nextState, exists := config.Transitions[guardIndex]; exists {
				context.Logger.Debug("guarded transition", "guard", guard.Name, "current", currentState, "next", nextState)

				return nextState, nil
			}
		}
	}

	return "", nil
}
