// This file is generated by VectorSigma . DO NOT EDIT.
package orderprocessor_test

import (
	"testing"

	"github.com/mhersson/vectorsigma/examples/error-events/orderprocessor"
)

func TestOrderProcessor_Run(t *testing.T) {
	type fields struct {
		Context       *orderprocessor.Context
		CurrentState  orderprocessor.StateName
		ExtendedState *orderprocessor.ExtendedState
		StateConfigs  map[orderprocessor.StateName]orderprocessor.StateConfig
	}
	tests := []struct {
		name   string
		fields fields
	}{
		{name: "Run the machine"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fsm := orderprocessor.New()
			fsm.Run()
		})
	}
}
