// Code generated by mockery v2.52.1. DO NOT EDIT.

package mock_shell

import mock "github.com/stretchr/testify/mock"

// MockCmdRunner is an autogenerated mock type for the CmdRunner type
type MockCmdRunner struct {
	mock.Mock
}

type MockCmdRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmdRunner) EXPECT() *MockCmdRunner_Expecter {
	return &MockCmdRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *MockCmdRunner) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCmdRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCmdRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockCmdRunner_Expecter) Run() *MockCmdRunner_Run_Call {
	return &MockCmdRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockCmdRunner_Run_Call) Run(run func()) *MockCmdRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmdRunner_Run_Call) Return(_a0 error) *MockCmdRunner_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCmdRunner_Run_Call) RunAndReturn(run func() error) *MockCmdRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCmdRunner creates a new instance of MockCmdRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmdRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmdRunner {
	mock := &MockCmdRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
