// This file is generated by VectorSigma v1.1.0-5-g68bd54d (commit: 68bd54d, built at: 2025-11-24T09:14:51Z.1.0). DO NOT EDIT.
package statemachine_test

import (
	"testing"

	"github.com/mhersson/vectorsigma/internal/statemachine"
)

func TestVectorSigma_Run(t *testing.T) {
	type fields struct {
		Context       *statemachine.Context
		CurrentState  statemachine.StateName
		ExtendedState *statemachine.ExtendedState
		StateConfigs  map[statemachine.StateName]statemachine.StateConfig
	}
	tests := []struct {
		name   string
		fields fields
	}{
		{name: "Run the machine"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fsm := statemachine.New()
			fsm.Run()
		})
	}
}
