// This file is generated by VectorSigma. DO NOT EDIT.
package statemachine_test

import (
	"github.com/mhersson/vectorsigma/internal/statemachine"
	"testing"
)

func TestVectorSigma_Run(t *testing.T) {
	type fields struct {
		Context       *statemachine.Context
		CurrentState  statemachine.StateName
		ExtendedState *statemachine.ExtendedState
		StateConfigs  map[statemachine.StateName]statemachine.StateConfig
	}
	tests := []struct {
		name   string
		fields fields
	}{
		{name: "Run the machine"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fsm := statemachine.New()
			fsm.Run()
		})
	}
}
